server:
  port: 5555
  servlet:
    context-path:  /blogs
spring:
  application:
    name: blogs-auth-service
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/HTML/
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8181/eureka/
  instance:
    hostname: blogs-auth-service
    appname: blogs-auth-service
headpictureurl: F:\head\
