server:
  port: 5000
spring:
  application:
    name: blogs-auth-service
eureka:
  client:
    service-url:
      defaltZone: http://localhost:8080/eureka/
  instance:
    hostname: blogs-auth-service