server:
  port: 5000
  servlet:
    context-path:  /blogs
spring:
  application:
    name: blogs-auth-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8181/eureka/
  instance:
    hostname: blogs-auth-service
    appname: blogs-auth-service

